### PR TITLE
Fix Awareness race condition

### PR DESCRIPTION
**Pull request by neftaly**
This fixes a missing "awareness" useCallback dependency in #6.

### CODE REVIEW

**Comment by neftaly** [comment]
Note that the same error will show if awareness data is set before provider connection is established, this is unrelated

**Comment by neftaly** [comment]
undid linting so this (and #11) can be merged quicker

**Comment by froger** [comment]
Thanks for the PRs @neftaly. All good to me, I've merged and published your fixes 0.0.12.

**Comment by kamikazebr** [comment]
> Note that the same error will show if awareness data is set before provider connection is established, this is unrelated

I noticed that, in internet slow, u can try set before connection `awareness` is done, and it give like undefined trying get `getLocalState()`

**Comment by froger** [comment]
> Note that the same error will show if awareness data is set before provider connection is established, this is unrelated

Just wanted to pass by to note that @kamikazebr fixed this "unrelated" bug in https://github.com/tandem-pt/zustand-yjs/pull/15. Thanks <3
cc @all-contributors.

**Pull request merged**
